// AUTOGENERADO - datos verificados del Mundial 2026 (sorteo 5-dic-2025 + repescas mar-2026)
window.WC = {
 "teams": {
  "mx": "México",
  "za": "Sudáfrica",
  "kr": "Corea del Sur",
  "cz": "Chequia",
  "ca": "Canadá",
  "ba": "Bosnia y Herzegovina",
  "qa": "Catar",
  "ch": "Suiza",
  "br": "Brasil",
  "ma": "Marruecos",
  "gb-sct": "Escocia",
  "ht": "Haití",
  "us": "Estados Unidos",
  "py": "Paraguay",
  "au": "Australia",
  "tr": "Turquía",
  "de": "Alemania",
  "cw": "Curazao",
  "ci": "Costa de Marfil",
  "ec": "Ecuador",
  "nl": "Países Bajos",
  "jp": "Japón",
  "se": "Suecia",
  "tn": "Túnez",
  "be": "Bélgica",
  "eg": "Egipto",
  "ir": "Irán",
  "nz": "Nueva Zelanda",
  "es": "España",
  "cv": "Cabo Verde",
  "sa": "Arabia Saudí",
  "uy": "Uruguay",
  "fr": "Francia",
  "sn": "Senegal",
  "iq": "Irak",
  "no": "Noruega",
  "ar": "Argentina",
  "dz": "Argelia",
  "at": "Austria",
  "jo": "Jordania",
  "pt": "Portugal",
  "cd": "RD Congo",
  "uz": "Uzbekistán",
  "co": "Colombia",
  "gb-eng": "Inglaterra",
  "hr": "Croacia",
  "gh": "Ghana",
  "pa": "Panamá"
 },
 "groups": {
  "A": [
   "mx",
   "za",
   "kr",
   "cz"
  ],
  "B": [
   "ca",
   "ba",
   "qa",
   "ch"
  ],
  "C": [
   "br",
   "ma",
   "gb-sct",
   "ht"
  ],
  "D": [
   "us",
   "py",
   "au",
   "tr"
  ],
  "E": [
   "de",
   "cw",
   "ci",
   "ec"
  ],
  "F": [
   "nl",
   "jp",
   "se",
   "tn"
  ],
  "G": [
   "be",
   "eg",
   "ir",
   "nz"
  ],
  "H": [
   "es",
   "cv",
   "sa",
   "uy"
  ],
  "I": [
   "fr",
   "sn",
   "iq",
   "no"
  ],
  "J": [
   "ar",
   "dz",
   "at",
   "jo"
  ],
  "K": [
   "pt",
   "cd",
   "uz",
   "co"
  ],
  "L": [
   "gb-eng",
   "hr",
   "gh",
   "pa"
  ]
 },
 "matches": [
  {
   "n": 1,
   "stage": "A",
   "venue": "Estadio Azteca",
   "city": "Ciudad de México",
   "off": -6,
   "utc": "2026-06-11T19:00:00Z",
   "home": "mx",
   "away": "za",
   "mxFree": true
  },
  {
   "n": 2,
   "stage": "A",
   "venue": "Estadio Akron",
   "city": "Guadalajara",
   "off": -6,
   "utc": "2026-06-12T02:00:00Z",
   "home": "kr",
   "away": "cz",
   "mxFree": false
  },
  {
   "n": 3,
   "stage": "B",
   "venue": "BMO Field",
   "city": "Toronto",
   "off": -4,
   "utc": "2026-06-12T19:00:00Z",
   "home": "ca",
   "away": "ba",
   "mxFree": false
  },
  {
   "n": 4,
   "stage": "D",
   "venue": "SoFi Stadium",
   "city": "Los Ángeles",
   "off": -7,
   "utc": "2026-06-13T01:00:00Z",
   "home": "us",
   "away": "py",
   "mxFree": false
  },
  {
   "n": 5,
   "stage": "C",
   "venue": "Gillette Stadium",
   "city": "Boston",
   "off": -4,
   "utc": "2026-06-14T01:00:00Z",
   "home": "ht",
   "away": "gb-sct",
   "mxFree": false
  },
  {
   "n": 6,
   "stage": "D",
   "venue": "BC Place",
   "city": "Vancouver",
   "off": -7,
   "utc": "2026-06-14T04:00:00Z",
   "home": "au",
   "away": "tr",
   "mxFree": false
  },
  {
   "n": 7,
   "stage": "C",
   "venue": "MetLife Stadium",
   "city": "Nueva York / Nueva Jersey",
   "off": -4,
   "utc": "2026-06-13T22:00:00Z",
   "home": "br",
   "away": "ma",
   "mxFree": true
  },
  {
   "n": 8,
   "stage": "B",
   "venue": "Levi's Stadium",
   "city": "Área de la Bahía de SF",
   "off": -7,
   "utc": "2026-06-13T19:00:00Z",
   "home": "qa",
   "away": "ch",
   "mxFree": false
  },
  {
   "n": 9,
   "stage": "E",
   "venue": "Lincoln Financial Field",
   "city": "Filadelfia",
   "off": -4,
   "utc": "2026-06-14T23:00:00Z",
   "home": "ci",
   "away": "ec",
   "mxFree": false
  },
  {
   "n": 10,
   "stage": "E",
   "venue": "NRG Stadium",
   "city": "Houston",
   "off": -5,
   "utc": "2026-06-14T17:00:00Z",
   "home": "de",
   "away": "cw",
   "mxFree": false
  },
  {
   "n": 11,
   "stage": "F",
   "venue": "AT&T Stadium",
   "city": "Dallas",
   "off": -5,
   "utc": "2026-06-14T20:00:00Z",
   "home": "nl",
   "away": "jp",
   "mxFree": true
  },
  {
   "n": 12,
   "stage": "F",
   "venue": "Estadio BBVA",
   "city": "Monterrey",
   "off": -6,
   "utc": "2026-06-15T02:00:00Z",
   "home": "se",
   "away": "tn",
   "mxFree": false
  },
  {
   "n": 13,
   "stage": "H",
   "venue": "Hard Rock Stadium",
   "city": "Miami",
   "off": -4,
   "utc": "2026-06-15T22:00:00Z",
   "home": "sa",
   "away": "uy",
   "mxFree": false
  },
  {
   "n": 14,
   "stage": "H",
   "venue": "Mercedes-Benz Stadium",
   "city": "Atlanta",
   "off": -4,
   "utc": "2026-06-15T16:00:00Z",
   "home": "es",
   "away": "cv",
   "mxFree": false
  },
  {
   "n": 15,
   "stage": "G",
   "venue": "SoFi Stadium",
   "city": "Los Ángeles",
   "off": -7,
   "utc": "2026-06-16T01:00:00Z",
   "home": "ir",
   "away": "nz",
   "mxFree": false
  },
  {
   "n": 16,
   "stage": "G",
   "venue": "Lumen Field",
   "city": "Seattle",
   "off": -7,
   "utc": "2026-06-15T19:00:00Z",
   "home": "be",
   "away": "eg",
   "mxFree": false
  },
  {
   "n": 17,
   "stage": "I",
   "venue": "MetLife Stadium",
   "city": "Nueva York / Nueva Jersey",
   "off": -4,
   "utc": "2026-06-16T19:00:00Z",
   "home": "fr",
   "away": "sn",
   "mxFree": false
  },
  {
   "n": 18,
   "stage": "I",
   "venue": "Gillette Stadium",
   "city": "Boston",
   "off": -4,
   "utc": "2026-06-16T22:00:00Z",
   "home": "iq",
   "away": "no",
   "mxFree": false
  },
  {
   "n": 19,
   "stage": "J",
   "venue": "Arrowhead Stadium",
   "city": "Kansas City",
   "off": -5,
   "utc": "2026-06-17T01:00:00Z",
   "home": "ar",
   "away": "dz",
   "mxFree": true
  },
  {
   "n": 20,
   "stage": "J",
   "venue": "Levi's Stadium",
   "city": "Área de la Bahía de SF",
   "off": -7,
   "utc": "2026-06-17T04:00:00Z",
   "home": "at",
   "away": "jo",
   "mxFree": false
  },
  {
   "n": 21,
   "stage": "L",
   "venue": "BMO Field",
   "city": "Toronto",
   "off": -4,
   "utc": "2026-06-17T23:00:00Z",
   "home": "gh",
   "away": "pa",
   "mxFree": false
  },
  {
   "n": 22,
   "stage": "L",
   "venue": "AT&T Stadium",
   "city": "Dallas",
   "off": -5,
   "utc": "2026-06-17T20:00:00Z",
   "home": "gb-eng",
   "away": "hr",
   "mxFree": true
  },
  {
   "n": 23,
   "stage": "K",
   "venue": "NRG Stadium",
   "city": "Houston",
   "off": -5,
   "utc": "2026-06-17T17:00:00Z",
   "home": "pt",
   "away": "cd",
   "mxFree": false
  },
  {
   "n": 24,
   "stage": "K",
   "venue": "Estadio Azteca",
   "city": "Ciudad de México",
   "off": -6,
   "utc": "2026-06-18T02:00:00Z",
   "home": "uz",
   "away": "co",
   "mxFree": false
  },
  {
   "n": 25,
   "stage": "A",
   "venue": "Mercedes-Benz Stadium",
   "city": "Atlanta",
   "off": -4,
   "utc": "2026-06-18T16:00:00Z",
   "home": "cz",
   "away": "za",
   "mxFree": false
  },
  {
   "n": 26,
   "stage": "B",
   "venue": "SoFi Stadium",
   "city": "Los Ángeles",
   "off": -7,
   "utc": "2026-06-18T19:00:00Z",
   "home": "ch",
   "away": "ba",
   "mxFree": false
  },
  {
   "n": 27,
   "stage": "B",
   "venue": "BC Place",
   "city": "Vancouver",
   "off": -7,
   "utc": "2026-06-18T22:00:00Z",
   "home": "ca",
   "away": "qa",
   "mxFree": false
  },
  {
   "n": 28,
   "stage": "A",
   "venue": "Estadio Akron",
   "city": "Guadalajara",
   "off": -6,
   "utc": "2026-06-19T01:00:00Z",
   "home": "mx",
   "away": "kr",
   "mxFree": true
  },
  {
   "n": 29,
   "stage": "C",
   "venue": "Lincoln Financial Field",
   "city": "Filadelfia",
   "off": -4,
   "utc": "2026-06-20T01:00:00Z",
   "home": "br",
   "away": "ht",
   "mxFree": false
  },
  {
   "n": 30,
   "stage": "C",
   "venue": "Gillette Stadium",
   "city": "Boston",
   "off": -4,
   "utc": "2026-06-19T22:00:00Z",
   "home": "gb-sct",
   "away": "ma",
   "mxFree": false
  },
  {
   "n": 31,
   "stage": "D",
   "venue": "Levi's Stadium",
   "city": "Área de la Bahía de SF",
   "off": -7,
   "utc": "2026-06-20T03:00:00Z",
   "home": "tr",
   "away": "py",
   "mxFree": false
  },
  {
   "n": 32,
   "stage": "D",
   "venue": "Lumen Field",
   "city": "Seattle",
   "off": -7,
   "utc": "2026-06-19T19:00:00Z",
   "home": "us",
   "away": "au",
   "mxFree": false
  },
  {
   "n": 33,
   "stage": "E",
   "venue": "BMO Field",
   "city": "Toronto",
   "off": -4,
   "utc": "2026-06-20T20:00:00Z",
   "home": "de",
   "away": "ci",
   "mxFree": false
  },
  {
   "n": 34,
   "stage": "E",
   "venue": "Arrowhead Stadium",
   "city": "Kansas City",
   "off": -5,
   "utc": "2026-06-21T00:00:00Z",
   "home": "ec",
   "away": "cw",
   "mxFree": false
  },
  {
   "n": 35,
   "stage": "F",
   "venue": "NRG Stadium",
   "city": "Houston",
   "off": -5,
   "utc": "2026-06-20T17:00:00Z",
   "home": "nl",
   "away": "se",
   "mxFree": false
  },
  {
   "n": 36,
   "stage": "F",
   "venue": "Estadio BBVA",
   "city": "Monterrey",
   "off": -6,
   "utc": "2026-06-21T04:00:00Z",
   "home": "tn",
   "away": "jp",
   "mxFree": false
  },
  {
   "n": 37,
   "stage": "H",
   "venue": "Hard Rock Stadium",
   "city": "Miami",
   "off": -4,
   "utc": "2026-06-21T22:00:00Z",
   "home": "uy",
   "away": "cv",
   "mxFree": false
  },
  {
   "n": 38,
   "stage": "H",
   "venue": "Mercedes-Benz Stadium",
   "city": "Atlanta",
   "off": -4,
   "utc": "2026-06-21T16:00:00Z",
   "home": "es",
   "away": "sa",
   "mxFree": false
  },
  {
   "n": 39,
   "stage": "G",
   "venue": "SoFi Stadium",
   "city": "Los Ángeles",
   "off": -7,
   "utc": "2026-06-21T19:00:00Z",
   "home": "be",
   "away": "ir",
   "mxFree": false
  },
  {
   "n": 40,
   "stage": "G",
   "venue": "BC Place",
   "city": "Vancouver",
   "off": -7,
   "utc": "2026-06-22T01:00:00Z",
   "home": "nz",
   "away": "eg",
   "mxFree": false
  },
  {
   "n": 41,
   "stage": "I",
   "venue": "MetLife Stadium",
   "city": "Nueva York / Nueva Jersey",
   "off": -4,
   "utc": "2026-06-23T00:00:00Z",
   "home": "no",
   "away": "sn",
   "mxFree": false
  },
  {
   "n": 42,
   "stage": "I",
   "venue": "Lincoln Financial Field",
   "city": "Filadelfia",
   "off": -4,
   "utc": "2026-06-22T21:00:00Z",
   "home": "fr",
   "away": "iq",
   "mxFree": false
  },
  {
   "n": 43,
   "stage": "J",
   "venue": "AT&T Stadium",
   "city": "Dallas",
   "off": -5,
   "utc": "2026-06-22T17:00:00Z",
   "home": "ar",
   "away": "at",
   "mxFree": false
  },
  {
   "n": 44,
   "stage": "J",
   "venue": "Levi's Stadium",
   "city": "Área de la Bahía de SF",
   "off": -7,
   "utc": "2026-06-23T03:00:00Z",
   "home": "jo",
   "away": "dz",
   "mxFree": false
  },
  {
   "n": 45,
   "stage": "L",
   "venue": "Gillette Stadium",
   "city": "Boston",
   "off": -4,
   "utc": "2026-06-23T20:00:00Z",
   "home": "gb-eng",
   "away": "gh",
   "mxFree": false
  },
  {
   "n": 46,
   "stage": "L",
   "venue": "BMO Field",
   "city": "Toronto",
   "off": -4,
   "utc": "2026-06-23T23:00:00Z",
   "home": "pa",
   "away": "hr",
   "mxFree": false
  },
  {
   "n": 47,
   "stage": "K",
   "venue": "NRG Stadium",
   "city": "Houston",
   "off": -5,
   "utc": "2026-06-23T17:00:00Z",
   "home": "pt",
   "away": "uz",
   "mxFree": false
  },
  {
   "n": 48,
   "stage": "K",
   "venue": "Estadio Akron",
   "city": "Guadalajara",
   "off": -6,
   "utc": "2026-06-24T02:00:00Z",
   "home": "co",
   "away": "cd",
   "mxFree": false
  },
  {
   "n": 49,
   "stage": "C",
   "venue": "Hard Rock Stadium",
   "city": "Miami",
   "off": -4,
   "utc": "2026-06-24T22:00:00Z",
   "home": "gb-sct",
   "away": "br",
   "mxFree": false
  },
  {
   "n": 50,
   "stage": "C",
   "venue": "Mercedes-Benz Stadium",
   "city": "Atlanta",
   "off": -4,
   "utc": "2026-06-24T22:00:00Z",
   "home": "ma",
   "away": "ht",
   "mxFree": false
  },
  {
   "n": 51,
   "stage": "B",
   "venue": "BC Place",
   "city": "Vancouver",
   "off": -7,
   "utc": "2026-06-24T19:00:00Z",
   "home": "ch",
   "away": "ca",
   "mxFree": false
  },
  {
   "n": 52,
   "stage": "B",
   "venue": "Lumen Field",
   "city": "Seattle",
   "off": -7,
   "utc": "2026-06-24T19:00:00Z",
   "home": "ba",
   "away": "qa",
   "mxFree": false
  },
  {
   "n": 53,
   "stage": "A",
   "venue": "Estadio Azteca",
   "city": "Ciudad de México",
   "off": -6,
   "utc": "2026-06-25T01:00:00Z",
   "home": "cz",
   "away": "mx",
   "mxFree": true
  },
  {
   "n": 54,
   "stage": "A",
   "venue": "Estadio BBVA",
   "city": "Monterrey",
   "off": -6,
   "utc": "2026-06-25T01:00:00Z",
   "home": "za",
   "away": "kr",
   "mxFree": false
  },
  {
   "n": 55,
   "stage": "E",
   "venue": "Lincoln Financial Field",
   "city": "Filadelfia",
   "off": -4,
   "utc": "2026-06-25T20:00:00Z",
   "home": "cw",
   "away": "ci",
   "mxFree": false
  },
  {
   "n": 56,
   "stage": "E",
   "venue": "MetLife Stadium",
   "city": "Nueva York / Nueva Jersey",
   "off": -4,
   "utc": "2026-06-25T20:00:00Z",
   "home": "ec",
   "away": "de",
   "mxFree": true
  },
  {
   "n": 57,
   "stage": "F",
   "venue": "AT&T Stadium",
   "city": "Dallas",
   "off": -5,
   "utc": "2026-06-25T23:00:00Z",
   "home": "jp",
   "away": "se",
   "mxFree": false
  },
  {
   "n": 58,
   "stage": "F",
   "venue": "Arrowhead Stadium",
   "city": "Kansas City",
   "off": -5,
   "utc": "2026-06-25T23:00:00Z",
   "home": "tn",
   "away": "nl",
   "mxFree": false
  },
  {
   "n": 59,
   "stage": "D",
   "venue": "SoFi Stadium",
   "city": "Los Ángeles",
   "off": -7,
   "utc": "2026-06-26T02:00:00Z",
   "home": "tr",
   "away": "us",
   "mxFree": false
  },
  {
   "n": 60,
   "stage": "D",
   "venue": "Levi's Stadium",
   "city": "Área de la Bahía de SF",
   "off": -7,
   "utc": "2026-06-26T02:00:00Z",
   "home": "py",
   "away": "au",
   "mxFree": false
  },
  {
   "n": 61,
   "stage": "I",
   "venue": "Gillette Stadium",
   "city": "Boston",
   "off": -4,
   "utc": "2026-06-26T19:00:00Z",
   "home": "no",
   "away": "fr",
   "mxFree": false
  },
  {
   "n": 62,
   "stage": "I",
   "venue": "BMO Field",
   "city": "Toronto",
   "off": -4,
   "utc": "2026-06-26T19:00:00Z",
   "home": "sn",
   "away": "iq",
   "mxFree": false
  },
  {
   "n": 63,
   "stage": "G",
   "venue": "Lumen Field",
   "city": "Seattle",
   "off": -7,
   "utc": "2026-06-27T03:00:00Z",
   "home": "eg",
   "away": "ir",
   "mxFree": false
  },
  {
   "n": 64,
   "stage": "G",
   "venue": "BC Place",
   "city": "Vancouver",
   "off": -7,
   "utc": "2026-06-27T03:00:00Z",
   "home": "nz",
   "away": "be",
   "mxFree": false
  },
  {
   "n": 65,
   "stage": "H",
   "venue": "NRG Stadium",
   "city": "Houston",
   "off": -5,
   "utc": "2026-06-27T00:00:00Z",
   "home": "cv",
   "away": "sa",
   "mxFree": false
  },
  {
   "n": 66,
   "stage": "H",
   "venue": "Estadio Akron",
   "city": "Guadalajara",
   "off": -6,
   "utc": "2026-06-27T00:00:00Z",
   "home": "uy",
   "away": "es",
   "mxFree": true
  },
  {
   "n": 67,
   "stage": "L",
   "venue": "MetLife Stadium",
   "city": "Nueva York / Nueva Jersey",
   "off": -4,
   "utc": "2026-06-27T21:00:00Z",
   "home": "pa",
   "away": "gb-eng",
   "mxFree": false
  },
  {
   "n": 68,
   "stage": "L",
   "venue": "Lincoln Financial Field",
   "city": "Filadelfia",
   "off": -4,
   "utc": "2026-06-27T21:00:00Z",
   "home": "hr",
   "away": "gh",
   "mxFree": false
  },
  {
   "n": 69,
   "stage": "J",
   "venue": "Arrowhead Stadium",
   "city": "Kansas City",
   "off": -5,
   "utc": "2026-06-28T02:00:00Z",
   "home": "dz",
   "away": "at",
   "mxFree": false
  },
  {
   "n": 70,
   "stage": "J",
   "venue": "AT&T Stadium",
   "city": "Dallas",
   "off": -5,
   "utc": "2026-06-28T02:00:00Z",
   "home": "jo",
   "away": "ar",
   "mxFree": false
  },
  {
   "n": 71,
   "stage": "K",
   "venue": "Hard Rock Stadium",
   "city": "Miami",
   "off": -4,
   "utc": "2026-06-27T23:30:00Z",
   "home": "co",
   "away": "pt",
   "mxFree": true
  },
  {
   "n": 72,
   "stage": "K",
   "venue": "Mercedes-Benz Stadium",
   "city": "Atlanta",
   "off": -4,
   "utc": "2026-06-27T23:30:00Z",
   "home": "cd",
   "away": "uz",
   "mxFree": false
  },
  {
   "n": 73,
   "stage": "R32",
   "venue": "SoFi Stadium",
   "city": "Los Ángeles",
   "off": -7,
   "utc": "2026-06-28T19:00:00Z",
   "home": "2A",
   "away": "2B",
   "mxFree": false
  },
  {
   "n": 74,
   "stage": "R32",
   "venue": "Gillette Stadium",
   "city": "Boston",
   "off": -4,
   "utc": "2026-06-29T20:30:00Z",
   "home": "1E",
   "away": "3(A/B/C/D/F)",
   "mxFree": false
  },
  {
   "n": 75,
   "stage": "R32",
   "venue": "Estadio BBVA",
   "city": "Monterrey",
   "off": -6,
   "utc": "2026-06-30T01:00:00Z",
   "home": "1F",
   "away": "2C",
   "mxFree": false
  },
  {
   "n": 76,
   "stage": "R32",
   "venue": "NRG Stadium",
   "city": "Houston",
   "off": -5,
   "utc": "2026-06-29T17:00:00Z",
   "home": "1C",
   "away": "2F",
   "mxFree": false
  },
  {
   "n": 77,
   "stage": "R32",
   "venue": "MetLife Stadium",
   "city": "Nueva York / Nueva Jersey",
   "off": -4,
   "utc": "2026-06-30T21:00:00Z",
   "home": "1I",
   "away": "3(C/D/F/G/H)",
   "mxFree": false
  },
  {
   "n": 78,
   "stage": "R32",
   "venue": "AT&T Stadium",
   "city": "Dallas",
   "off": -5,
   "utc": "2026-06-30T17:00:00Z",
   "home": "2E",
   "away": "2I",
   "mxFree": false
  },
  {
   "n": 79,
   "stage": "R32",
   "venue": "Estadio Azteca",
   "city": "Ciudad de México",
   "off": -6,
   "utc": "2026-07-01T01:00:00Z",
   "home": "1A",
   "away": "3(C/E/F/H/I)",
   "mxFree": false
  },
  {
   "n": 80,
   "stage": "R32",
   "venue": "Mercedes-Benz Stadium",
   "city": "Atlanta",
   "off": -4,
   "utc": "2026-07-01T16:00:00Z",
   "home": "1L",
   "away": "3(E/H/I/J/K)",
   "mxFree": false
  },
  {
   "n": 81,
   "stage": "R32",
   "venue": "Levi's Stadium",
   "city": "Área de la Bahía de SF",
   "off": -7,
   "utc": "2026-07-02T00:00:00Z",
   "home": "1D",
   "away": "3(B/E/F/I/J)",
   "mxFree": false
  },
  {
   "n": 82,
   "stage": "R32",
   "venue": "Lumen Field",
   "city": "Seattle",
   "off": -7,
   "utc": "2026-07-01T20:00:00Z",
   "home": "1G",
   "away": "3(A/E/H/I/J)",
   "mxFree": false
  },
  {
   "n": 83,
   "stage": "R32",
   "venue": "BMO Field",
   "city": "Toronto",
   "off": -4,
   "utc": "2026-07-02T23:00:00Z",
   "home": "2K",
   "away": "2L",
   "mxFree": false
  },
  {
   "n": 84,
   "stage": "R32",
   "venue": "SoFi Stadium",
   "city": "Los Ángeles",
   "off": -7,
   "utc": "2026-07-02T19:00:00Z",
   "home": "1H",
   "away": "2J",
   "mxFree": false
  },
  {
   "n": 85,
   "stage": "R32",
   "venue": "BC Place",
   "city": "Vancouver",
   "off": -7,
   "utc": "2026-07-03T03:00:00Z",
   "home": "1B",
   "away": "3(E/F/G/I/J)",
   "mxFree": false
  },
  {
   "n": 86,
   "stage": "R32",
   "venue": "Hard Rock Stadium",
   "city": "Miami",
   "off": -4,
   "utc": "2026-07-03T22:00:00Z",
   "home": "1J",
   "away": "2H",
   "mxFree": false
  },
  {
   "n": 87,
   "stage": "R32",
   "venue": "Arrowhead Stadium",
   "city": "Kansas City",
   "off": -5,
   "utc": "2026-07-04T01:30:00Z",
   "home": "1K",
   "away": "3(D/E/I/J/L)",
   "mxFree": false
  },
  {
   "n": 88,
   "stage": "R32",
   "venue": "AT&T Stadium",
   "city": "Dallas",
   "off": -5,
   "utc": "2026-07-03T18:00:00Z",
   "home": "2D",
   "away": "2G",
   "mxFree": false
  },
  {
   "n": 89,
   "stage": "R16",
   "venue": "Lincoln Financial Field",
   "city": "Filadelfia",
   "off": -4,
   "utc": "2026-07-04T21:00:00Z",
   "home": "G74",
   "away": "G77",
   "mxFree": false
  },
  {
   "n": 90,
   "stage": "R16",
   "venue": "NRG Stadium",
   "city": "Houston",
   "off": -5,
   "utc": "2026-07-04T17:00:00Z",
   "home": "G73",
   "away": "G75",
   "mxFree": false
  },
  {
   "n": 91,
   "stage": "R16",
   "venue": "MetLife Stadium",
   "city": "Nueva York / Nueva Jersey",
   "off": -4,
   "utc": "2026-07-05T20:00:00Z",
   "home": "G76",
   "away": "G78",
   "mxFree": false
  },
  {
   "n": 92,
   "stage": "R16",
   "venue": "Estadio Azteca",
   "city": "Ciudad de México",
   "off": -6,
   "utc": "2026-07-06T00:00:00Z",
   "home": "G79",
   "away": "G80",
   "mxFree": false
  },
  {
   "n": 93,
   "stage": "R16",
   "venue": "AT&T Stadium",
   "city": "Dallas",
   "off": -5,
   "utc": "2026-07-06T19:00:00Z",
   "home": "G83",
   "away": "G84",
   "mxFree": false
  },
  {
   "n": 94,
   "stage": "R16",
   "venue": "Lumen Field",
   "city": "Seattle",
   "off": -7,
   "utc": "2026-07-07T00:00:00Z",
   "home": "G81",
   "away": "G82",
   "mxFree": false
  },
  {
   "n": 95,
   "stage": "R16",
   "venue": "Mercedes-Benz Stadium",
   "city": "Atlanta",
   "off": -4,
   "utc": "2026-07-07T16:00:00Z",
   "home": "G86",
   "away": "G88",
   "mxFree": false
  },
  {
   "n": 96,
   "stage": "R16",
   "venue": "BC Place",
   "city": "Vancouver",
   "off": -7,
   "utc": "2026-07-07T20:00:00Z",
   "home": "G85",
   "away": "G87",
   "mxFree": false
  },
  {
   "n": 97,
   "stage": "QF",
   "venue": "Gillette Stadium",
   "city": "Boston",
   "off": -4,
   "utc": "2026-07-09T20:00:00Z",
   "home": "G89",
   "away": "G90",
   "mxFree": false
  },
  {
   "n": 98,
   "stage": "QF",
   "venue": "SoFi Stadium",
   "city": "Los Ángeles",
   "off": -7,
   "utc": "2026-07-10T19:00:00Z",
   "home": "G93",
   "away": "G94",
   "mxFree": false
  },
  {
   "n": 99,
   "stage": "QF",
   "venue": "Hard Rock Stadium",
   "city": "Miami",
   "off": -4,
   "utc": "2026-07-11T21:00:00Z",
   "home": "G91",
   "away": "G92",
   "mxFree": false
  },
  {
   "n": 100,
   "stage": "QF",
   "venue": "Arrowhead Stadium",
   "city": "Kansas City",
   "off": -5,
   "utc": "2026-07-12T01:00:00Z",
   "home": "G95",
   "away": "G96",
   "mxFree": false
  },
  {
   "n": 101,
   "stage": "SF",
   "venue": "AT&T Stadium",
   "city": "Dallas",
   "off": -5,
   "utc": "2026-07-14T19:00:00Z",
   "home": "G97",
   "away": "G98",
   "mxFree": true
  },
  {
   "n": 102,
   "stage": "SF",
   "venue": "Mercedes-Benz Stadium",
   "city": "Atlanta",
   "off": -4,
   "utc": "2026-07-15T19:00:00Z",
   "home": "G99",
   "away": "G100",
   "mxFree": true
  },
  {
   "n": 103,
   "stage": "3P",
   "venue": "Hard Rock Stadium",
   "city": "Miami",
   "off": -4,
   "utc": "2026-07-18T21:00:00Z",
   "home": "P101",
   "away": "P102",
   "mxFree": true
  },
  {
   "n": 104,
   "stage": "F",
   "venue": "MetLife Stadium",
   "city": "Nueva York / Nueva Jersey",
   "off": -4,
   "utc": "2026-07-19T19:00:00Z",
   "home": "G101",
   "away": "G102",
   "mxFree": true
  }
 ]
};
